blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('blog/view/<int:pk>/', BlogDetailView.as_view(), name='article_detail')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView, \
    MailingDetailView, ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, MessageListView, \
    MessageCreateView, MessageUpdateView, MessageDeleteView, MessageDetailView, MainView

app_name = MailingConfig.name

urlpatterns =[
    path('', cache_page(60)(MainView.as_view()), name='index'),
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/create/', MailingCreateView.as_view(), name='create_mailing'),
    path('mailing/update/<int:pk>/', MailingUpdateView.as_view(), name='update_mailing'),
    path('mailing/delete/<int:pk>/', MailingDeleteView.as_view(), name='delete_mailing'),
    path('mailing/view/<int:pk>/', MailingDetailView.as_view(), name='view_mailing'),

    path('client/', ClientListView.as_view(), name='client_list'),
    path('client/create/', ClientCreateView.as_view(), name='create_client'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),

    path('message/', MessageListView.as_view(), name='message_list'),
    path('message/create/', MessageCreateView.as_view(), name='create_message'),
    path('message/update/<int:pk>/', MessageUpdateView.as_view(), name='update_message'),
    path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),
    path('message/view/<int:pk>/', MessageDetailView.as_view(), name='view_message'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(),name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register')
]

mailing/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(max_length=150, unique=True, verbose_name='почта')
    name = models.CharField(max_length=150, verbose_name='имя')
    surname = models.CharField(max_length=150, verbose_name='фамилия', **NULLABLE)
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)

    def __str__(self):
        return f'{self.email} - {self.name}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Message(models.Model):
    title = models.CharField(max_length=150, verbose_name='тема')
    body = models.TextField(verbose_name='сообщение')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Mailing(models.Model):

    DAILY = 'daily'
    WEEKLY = 'weekly'
    MONTHLY = 'monthly'

    PERIODS = [
        (DAILY, 'раз в день'),
        (WEEKLY, 'раз в неделю'),
        (MONTHLY, 'раз в месяц'),
    ]

    CREATED = 'created'
    STARTED = 'started'
    DONE = 'done'

    STATUSES = [
        (CREATED, 'создана'),
        (STARTED, 'выполняется'),
        (DONE, 'завершена'),
    ]

    time_start = models.DateTimeField(verbose_name='время старта')
    time_end = models.DateTimeField(verbose_name='время окончания')
    period = models.CharField(default=DAILY, max_length=15, choices=PERIODS, verbose_name='периодичность')
    status = models.CharField(default=CREATED, max_length=15, choices=STATUSES, verbose_name='статус')

    client = models.ManyToManyField(Client, verbose_name='клиент')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='сообщение')

    def __str__(self):
        return f'С {self.time_start} по {self.time_end}: {self.period}, {self.status}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки '


class Logs(models.Model):

    SENT = 'sent'
    FAILED = 'failed'
    PENDING = 'pending'

    STATUS = [
        (SENT, 'Отправлено'),
        (FAILED, 'Не удалось отправить'),
        (PENDING, 'В ожидании')
    ]

    date = models.DateTimeField(auto_now_add=True, verbose_name='время последней попытки')
    status = models.CharField(max_length=50, choices=STATUS, default=PENDING, verbose_name='статус попытки')
    response = models.CharField(max_length=250, verbose_name='ответ почтового сервера', **NULLABLE)

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка', **NULLABLE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='клиент рассылки', **NULLABLE)

    def __str__(self):
        return f'{self.date} - {self.status}'

    class Meta:
        verbose_name = 'лог рассылки'
        verbose_name_plural = 'логи рассылки'

mailing/forms.py
from django import forms

from mailing.models import Mailing, Client, Message


class StyleFormMixin():

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Mailing
        exclude = ('status', 'client')


class ClientForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Client
        fields = ('email', 'name', 'surname',)


class MessageForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Message
        fields = ('title', 'body',)

mailing/views.py
import random

from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, TemplateView

from blog.models import Article
from mailing.forms import MailingForm, ClientForm, MessageForm
from mailing.models import Mailing, Client, Message


# def index(request):
#     context = {
#         'title': 'Сервис рассылок'
#     }
#     if request.method == 'GET':
#         return render(request, 'mailing/index.html', context)

class MainView(LoginRequiredMixin, TemplateView):
    template_name = 'mailing/index.html'

    def get_context_data(self, **kwargs):

        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Сервис рассылок'

        context_data['mailing'] = len(Mailing.objects.all())
        context_data['started_mailing'] = Mailing.objects.filter(status=Mailing.STARTED).count()
        context_data['client'] = len(Client.objects.all())
        context_data['object_list'] = random.sample(list(Article.objects.all()), 3)

        return context_data


class MailingListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Mailing
    permission_required = 'mailing.view_mailing'
    extra_context = {
        'title': 'Рассылки'
    }


class MailingCreateView(PermissionRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    permission_required = 'mailing.add_mailing'
    success_url = reverse_lazy('mailing:mailing_list')


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingForm

    def get_success_url(self):
        return reverse('mailing:update_mailing', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.client != self.request.user:
            raise Http404
        return self.object


class MailingDeleteView(PermissionRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')
    permission_required = 'mailing.delete_mailing'


class MailingDetailView(DetailView):
    model = Mailing
    template_name = 'mailing/mailing_detail.html'


class ClientListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Client
    permission_required = 'mailing.view_client'
    extra_context = {
        'title': 'Клиенты'
    }


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse('mailing:update_client', args=[self.kwargs.get('pk')])


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client_list')


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    extra_context = {
        'title': 'Сообщения для рассылок'
    }


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')


class MessageUpdateView(PermissionRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    permission_required = 'mailing.change_message'

    def get_success_url(self):
        return reverse('mailing:update_message', args=[self.kwargs.get('pk')])


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:message_list')


class MessageDetailView(DetailView):
    model = Message
    template_name = 'mailing/message_detail.html'

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Сервис рассылок</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
    </style>


</head>
<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-7 py-4">
                    <h4 class="text-white">Сервис рассылок</h4>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'mailing:index' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'mailing:mailing_list' %}" class="text-white">Рассылки</a></li>
                        <li><a href="{% url 'mailing:message_list' %}" class="text-white">Сообщения для рассылок</a></li>
                        <li><a href="{% url 'mailing:client_list' %}" class="text-white">Клиенты</a></li>
                        <li><a href="{% url 'blog:blog_list' %}" class="text-white">Блог</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'users:logout' %}" class="text-white">Выход</a></li>
                        {% else %}
                            <li><a href="{% url 'users:login' %}" class="text-white">Вход</a></li>
                            <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="#" class="navbar-brand d-flex align-items-center"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">{{ title }}</h1>
            </div>
        </div>
    </section>
    {% block content %}
    {% endblock %}
</main>

<footer class="text-muted py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Вверх</a>
        </p>
        <p class="mb-1">На нашем сервисе Вы можете зарегистрироваться и выбрать актуальные для вас рассылки.</p>
        <p class="mb-0">
            <a href="#">Регистрация</a>
            <br>
            <a href="{% url 'mailing:mailing_list' %}">Рассылки</a>
        </p>
    </div>
</footer>


<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h5>Хотите удалить карточку клиента {{ object.name|title }} {{ object.surname|title }}?</h5>
                        <button type="submit" class="btn btn-outline-danger">Подтвердить</button>
                        <a href="{% url 'mailing:client_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-12">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card">
                <div class="card-title">
                    {% if object %}
                    <h3>Изменить карточку клиента</h3>
                    {% else %}
                    <h3>Создать карточку клиента</h3>
                    {% endif %}
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                    <a href="{% url 'mailing:client_list' %}" class="btn btn-primary">К списку клиентов</a>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html'%}

{% block content %}

<div class="album py-5 bg-light">
    <div class="container">
        <div class="col-12 mb-5 ">
            <a class="btn btn-primary" href="{% url 'mailing:create_client' %}">Добавить клиента</a>
        </div>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">

                <div class="card shadow-sm">
                    <div class="card-body">
                        <p>Имя клиента - {{ object.name|title }}</p>
                        <p>Фамилия клиента - {{ object.surname|title }}</p>
                        <p>Электронная почта - {{ object.email }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'mailing:update_client' object.pk %}">Изменить</a>
                                <a class="btn btn-outline-danger float-right"
                                   href="{% url 'mailing:delete_client' object.pk %}">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html'%}

{% block content %}


<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-10">
            <div class="col">
                <div class="card shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Рассылки"
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"/>
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em">Рассылки</text>
                    </svg>

                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'mailing:mailing_list' %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">К рассылкам</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

             <div class="col">
                <div class="card shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Рассылки"
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"/>
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em">Сообщения</text>
                    </svg>

                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'mailing:message_list' %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">К сообщениям</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <div class="col">

                <div class="card shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Клиенты"
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"/>
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em">Клиенты</text>
                    </svg>

                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'mailing:client_list' %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">К клиентам</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <br>


    <div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"/>
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ object.title }}</text>
                    </svg>

                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'blog:article_detail' object.pk %}">Читать</a>
                            </div>
                        </div>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Просмотры: {{object.view_count}}</li>
                        <li>Дата публикации: {{object.date_published}}</li>
                        </ul>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

    <div class="container-fluid">
        <div class="row text-center">
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Количество рассылок всего</td>
                                <td>{{ mailing }}</td>
                            </tr>
                            <tr>
                                <td class="w-25">Количество активных рассылок</td>
                                <td>{{ started_mailing }}</td>
                            </tr>
                            <tr>
                                <td class="w-25">Количество уникальных клиентов для рассылок</td>
                                <td>{{ client }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
 </div>

{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h5>Хотите удалить рассылку "{{ object.message }}"?</h5>
                        <button type="submit" class="btn btn-outline-danger">Подтвердить</button>
                        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}


{% block content %}
<div class="container">

            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    <div class="card-title">
                        <h5 class="card-title">Рассылка "{{ object.message }}"</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text">Дата начала рассылки - {{ object.time_start }}</p>
                        <p class="card-text">Дата окончания рассылки - {{ object.time_start }}</p>
                        <p class="card-text">Периодичность - {{ object.period }}</p>
                        <p class="card-text">Статус - {{ object.status|default:"Создана" }}</p>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-primary" href="{% url 'mailing:update_mailing' object.pk %}">Редактировать</a>
                    </div>
                </div>
            </div>

</div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-12">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card">
                <div class="card-title">
                    {% if object %}
                    <h3>Изменить рассылку</h3>
                    {% else %}
                    <h3>Создание рассылки</h3>
                    {% endif %}
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                    <a href="{% url 'mailing:mailing_list' %}" class="btn btn-primary">К рассылкам</a>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html'%}

{% block content %}

<div class="album py-5 bg-light">
    <div class="container">
        <div class="col-12 mb-5 ">
            <a class="btn btn-primary" href="{% url 'mailing:create_mailing' %}">Добавить рассылку</a>
        </div>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">

                <div class="card shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"/>
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ object.message }}</text>
                    </svg>

                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'mailing:view_mailing' object.pk %}">Подробнее</a>
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'mailing:update_mailing' object.pk %}">Изменить</a>
                                <a class="btn btn-outline-danger float-right"
                                   href="{% url 'mailing:delete_mailing' object.pk %}">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h5>Хотите удалить сообщение для рассылки "{{ object.title }}"?</h5>
                        <button type="submit" class="btn btn-outline-danger">Подтвердить</button>
                        <a href="{% url 'mailing:message_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}


{% block content %}
<div class="container">

            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    <div class="card-title">
                        <h5 class="card-title">Рассылка "{{ object.title }}"</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text">Текст рассылки - {{ object.body }}</p>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-primary" href="{% url 'mailing:update_message' object.pk %}">Редактировать</a>
                    </div>
                </div>
            </div>

</div>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html'%}

{% block content %}

<div class="album py-5 bg-light">
    <div class="container">
        <div class="col-12 mb-5 ">
            <a class="btn btn-primary" href="{% url 'mailing:create_message' %}">Добавить сообщение</a>
        </div>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">

                <div class="card shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"/>
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ object.body }}</text>
                    </svg>

                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'mailing:view_message' object.pk %}">Подробнее</a>
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'mailing:update_message' object.pk %}">Изменить</a>
                                <a class="btn btn-outline-danger float-right"
                                   href="{% url 'mailing:delete_message' object.pk %}">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}